---
# Ansible variables
  
-   hosts: localhost
    vars:
        salary: 10000
        car_model: 'BMW M3'
        country_name: USA
        title: 'Systems Engineer'
    tasks:
        -
            command: 'echo "My car''s model is {{ car_model }}"'
            when: salary == 10000
        -
            command: 'echo "I live in the {{ country_name }}"'

        -
            command: 'echo "I work as a {{ title }}"'
