---

- name: Setup
  hosts: server_node1
  remote_user: root
  tasks:
    # 1. check if 1pv6 is enabled ifconfig |grep inet6
    # 2. edit vi /etc/sysctl.conf and append
    # net.ipv6.conf.all.disable_ipv6 = 1
    # net.ipv6.conf.default.disable_ipv6 = 1
    # 3.apply changes sysctl -p
    # 4 . check if 1pv6 is enabled ifconfig |grep inet6
      - name: Disable IPv6 with sysctl
        sysctl:
           name: {{ item }}
           value: 1
           state: present
           reload: yes

        with_items:
          - net.ipv6.conf.all.disable_ipv6
          - net.ipv6.conf.default.disable_ipv6
          - net.ipv6.conf.lo.disable_ipv6
# 1. check updates - sudo yum check-update
# 2. refresh package and install update - sudo yum update
# 3. reboot system - sudo reboot
      - name: config root pw
        shell: echo "create root pw {{ root_password | default("hallo") | password_hash("sha512", "ks7d") }}"

      - name: Upload ssh Key
        authorized_key:
          user: root
          state: present
          key: "{{ lookup('file', '~/.ssh/id_rsa.pub')}}"
      - name: restart sshd
        service:
          name: sshd
          state: restarted

      - name: update the packages
        yum:
          state: latest
          update_cache: yes  # Force yum to check if cache is out of date and redownload if needed.
          update_only: yes   # When using latest, only update installed packages.
          

# Connect to the server via SSH as the root user; or open a terminal if you’re working locally.
# Install the EPEL repository with the following command: sudo yum install epel-release
# Confirm your work and refresh the repo list by running: sudo yum repolist
      - name: install epel-release
        yum:
          name: epel-release
          state: latest

# For remote CentOS 8 server login using ssh command.
# Turn on EPEL repo
# Execute sudo yum search htop command to search for htop on CentOS
# Run sudo yum install htop to install htop in CentOS 8
# Update sudo yum update htop to upgrade htop to the latest version in CentOS 8

      - name: install htop on centos
        yum:
          name: htop
          state: present
