---
- hosts: first-test-vm
  gather_facts: no
  tasks:
    - name: Update Root user's Password
      user:
        name: root
        update_password: always
        password: create root pw {{ root_password | default("hallo") | password_hash("sha512", "ks7d") }}
