---
# For remote CentOS 8 server login using ssh command.
# Turn on EPEL repo
# Execute sudo yum search htop command to search for htop on CentOS
# Run sudo yum install htop to install htop in CentOS 8
# Update sudo yum update htop to upgrade htop to the latest version in CentOS 8

- name: install htop on centos
  yum:
    name: htop
    state: installed

- name: enable htop
  yum:
    name: htop
    state: started
