---

- name: Upload root ssh Key
  authorized_key:
    user: "root"
    key: "{{ item.key }}"
    comment: "{{ item.comment }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ ssh_users_admins.authorized_keys }}"

- name: Update Root user's Password
  user:
    name: root
    update_password: always
    password: create root pw {{ root_password | default("hallo") | password_hash("sha512", "ks7d") }}
